# Generated by Django 3.1.4 on 2021-01-12 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excercice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('sujet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.TextField(blank=True, null=True)),
                ('legal', models.BooleanField(default=False)),
                ('corrected', models.BooleanField(default=False)),
                ('excercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schreiben.excercice')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('remarque', models.TextField()),
                ('reponse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schreiben.reponse')),
            ],
        ),
    ]
