# Generated by Django 3.1.4 on 2021-01-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schreiben', '0002_auto_20201229_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='corps',
            field=models.TextField(blank=True),
        ),
    ]
