# Generated by Django 3.1.4 on 2021-01-07 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('subject', models.TextField()),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.personne')),
            ],
        ),
    ]
