# Generated by Django 3.1.4 on 2021-01-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('datedenaissance', models.CharField(default='02-01-2002', max_length=50)),
                ('username', models.CharField(max_length=18)),
                ('Address', models.CharField(max_length=80)),
                ('Sexe', models.CharField(max_length=5)),
                ('photo', models.ImageField(default='pictures/user_200_200.jpg', max_length=255, upload_to='pictures/')),
                ('succes_schreiben', models.IntegerField(default=0)),
                ('succes_lesen', models.IntegerField(default=0)),
                ('succes_horen', models.IntegerField(default=0)),
                ('succes_grammar', models.IntegerField(default=0)),
                ('datecreationaccount', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='temporals',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.personne')),
            ],
        ),
    ]
