# Generated by Django 2.2.17 on 2020-12-19 18:11

import Auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(Auth.models.Personne, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25)),
                ('passord', models.CharField(max_length=25)),
            ],
            bases=(Auth.models.Personne, models.Model),
        ),
        migrations.CreateModel(
            name='Succes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('succes_schreiben', models.IntegerField()),
                ('succes_lesen', models.IntegerField()),
                ('succes_horen', models.IntegerField()),
                ('succes_grammar', models.IntegerField()),
                ('users', models.ManyToManyField(blank=True, related_name='succes', to='Auth.User')),
            ],
        ),
    ]
