# Generated by Django 3.1.4 on 2020-12-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('datedenaissance', models.CharField(default='02-01-2002', max_length=50)),
                ('username', models.CharField(max_length=18)),
                ('telephone', models.CharField(default='0652518306', max_length=18)),
                ('succes_schreiben', models.IntegerField(default=0)),
                ('succes_lesen', models.IntegerField(default=0)),
                ('succes_horen', models.IntegerField(default=0)),
                ('succes_grammar', models.IntegerField(default=0)),
                ('datecreationaccount', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
