# Generated by Django 3.1.4 on 2020-12-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='telephone',
            field=models.CharField(default='0652518306', max_length=18),
        ),
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='personne',
            name='password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='personne',
            name='username',
            field=models.CharField(max_length=18),
        ),
    ]
