# Generated by Django 3.1.4 on 2020-12-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passord',
            new_name='password',
        ),
    ]
