# Generated by Django 3.1.4 on 2020-12-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20201214_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='datedenaissance',
            field=models.CharField(default='02-01-2002', max_length=50),
        ),
    ]
