# Generated by Django 3.1.4 on 2020-12-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_personne_datedenaissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='datecreationaccount',
            field=models.DateField(auto_now_add=True),
        ),
    ]
